
jQuery ->
  ###
    Treatment of <label>s in #macro-search-form. The <label>s have been 
    generated by formtastic. So, one way or the other, we have to handle them
  ###

  for label in $('#macro-search-form').find 'label'
    #$(label).addClass 'inline-label'
    $(label).addClass 'hidden'

  ###
    Clicking new-quiz-link
  ###
  $('#new-quiz-link').click ->
