
jQuery ->
  ###
    Treatment of <label>s in #macro-search-form. The <label>s have been 
    generated by formtastic. So, one way or the other, we have to handle them
  ###

  for label in $('#macro-search-form').find 'label'
    #$(label).addClass 'inline-label'
    $(label).addClass 'hidden'

  ###
    Clicking new-quiz-link
  ###
  $('#new-quiz-link').click ->
    # Append the micro-topic-list inside #micro-select-form > form
    microTopics = $('#toolbox').children('#micro-topic-list').detach()
    form = $('#micro-select-form > form:first')
    microTopics.appendTo form
    
    # Customize the swiss-knives within the form 
    for item in form.find '.swiss-knife'
      swissKnife.customize $(item), {radio:true}, true

