
# Sample YAML 
#
#  lnk-something : 
#    show : 
#      left : 
#      middle : 
#      right : 
#      wide : 
#      modal : 
#      menu :
#      help : 
#      video : true / false 
#    autoclick : 
#      tab : 
#      link :
#    url : 
#      self : 
#      panel :
#    paginate-on: line/tab/sth. else
#    default : true / false
#    ajax : disabled / enabled 
#    prev : 
#    id : 
#    update-on : < list of URLs >
#    disable-if : key ( => json.key is true ) 
#    disable-unless : key ( => json.key is false )
#    callback : 
#     pre :    -> pre click
#     post :   -> post click
#    childtabs : 
#     reset : true | false -> unclick child tabs or not before clicking first one
#

m-customer-options :
  show : 
    menu : customer-main

lnk-buy-credits :
  show :
    modal : m-buy-credits

lnk-refund-credits :
  show :
    modal : m-refund-credits

lnk-xfer-credits :
  show :
    modal : m-transfer

lnk-see-activity :
  autoclick : 
    tab : tab-see-activity
  show : 
    left : left-4
    wide : wide-3

tab-see-activity :
  url :
    self : customer/activity
    panel : document/transactions?id=:id

lnk-gen-invoice :
  show :
    modal : m-invoice

lnk-customer-list :
  autoclick : 
    tab : tab-cust
  show : 
    left : left-9

tab-cust :
  url :
    self : customers/list


