
# Sample YAML 
#
#  lnk-something : 
#    show : 
#      left : 
#      middle : 
#      right : 
#      wide : 
#      modal : 
#      menu :
#      help : 
#      video : true / false 
#    autoclick : 
#      tab : 
#      link :
#    url : 
#      self : 
#      panel :
#    paginate-on: line/tab/sth. else
#    default : true / false
#    ajax : disabled / enabled 
#    prev : 
#    id : 
#    update-on : < list of URLs >
#    disable-if : key ( => json.key is true ) 
#    disable-unless : key ( => json.key is false )
#    callback : 
#     pre :    -> pre click
#     post :   -> post click
#    childtabs : 
#     reset : true | false -> unclick child tabs or not before clicking first one
#

##############################################################################
## Admin / Examiner specific  
##############################################################################

a-indie-main :
  default : true 
  show : 
    left : left-12 
    wide : wide-Y 
  autoclick : 
    tab : tab-doubts-1

a-grade-exams :
  show : 
    left : left-4
    wide : wide-X
  autoclick :
    tab : tab-grade-1

lnk-dispute-reason : 
  url :
    self : dispute/reason?id=:a
  update-on: load/dispute

lnk-wb-disputes :
  show : 
    left : left-10
    wide: wide-X
  autoclick :
    tab : tab-disputes

tab-disputes : 
  url :
    self : disputes
    panel : load/dispute?id=:id

lnk-reject-dispute :
  show : 
    modal : m-reject-dispute 

lnk-accept-dispute :
  url: 
    self : dispute/accept?id=:a
  update-on: load/dispute

lnk-audit-close : 
  update-on: question/preview
  url : 
    self : audit/close?id=:a

m-admin-wb :
  show : 
    menu : admin-wb

m-admin-schools :
  show : 
    menu : admin-schools 

lnk-wb-receive :
  url : 
    self : receive/scans

lnk-wb-apprentices : 
  show : 
    left : left-9
    wide : wide-X
  autoclick :
    tab : tab-apprentices

tab-apprentices :
  url :
    self : examiner/apprentices
    panel : load/samples?id=:id

lnk-audit-apprentice : 
  show : 
    modal : m-audit-apprentice

lnk-wb-schools :
  show : 
    left : left-1
    wide : wide-1
  url : 
    self : schools/list

lnk-wb-blockdb :
  url : 
    self : examiner/block_db_slots.json?id=:id
  id : control-panel

m-examiner-wb :
  show : 
    menu : examiner-wb

lnk-wb-tagging :
  show : 
    left : left-3
    wide : wide-X
  autoclick :
    tab : tab-untagged-1

tab-untagged-1 :
  url : 
    self : untagged/list
    panel : question/preview?id=:id&context=tag
  autoclick :
    tab : tab-untagged-2

tab-tag-* : 
  url : 
    self : vertical/topics?id=:id&context=tag
    panel : set/topic?q=:prev&t=:id
  prev : tab-untagged-1
  autoclick : 
    tab : tab-untagged-3

lnk-wb-typeset :
  show : 
    left : left-5
    wide : wide-X
  autoclick :
    tab : tab-typeset-new

tab-typeset-new :
  url : 
    self : typeset/new
    panel : suggestion/preview.json?id=:id

lnk-block-* : 
  id : tab-typeset-new

m-block-slots :
  show : 
    menu : blockdb-slots

tab-typeset-ongoing :
  url : 
    self : typeset/ongoing
    panel : question/preview.json?id=:id

lnk-wb-resolve :
  show : 
    left : left-6
    wide : wide-X
  autoclick : 
    tab : tab-resolution-pending

lnk-wb-audit :
  show : 
    left : left-7
    wide : wide-X
  autoclick : 
    tab : tab-audit-2

lnk-wb-add-videos :
  show : 
    left : left-8
    wide : wide-X
  autoclick : 
    tab : tab-video-pending

tab-video-pending : 
  url : 
    self : questions/without_video
    panel : question/preview.json?id=:id

lnk-audit-form : 
  show : 
    modal : m-audit-form

tab-audit-1 : 
  url : 
    self : audit/todo
    panel : question/preview.json?id=:id&context=audit

tab-audit-2 : 
  url : 
    self : audit/review
    panel : question/preview.json?id=:id&context=audit

tab-audit-4 : 
  url : 
    panel : question/preview?id=:id&context=addhints

tab-addhints-* : 
  url : 
    self : vertical/topics?id=:id&context=addhints
    panel : questions/on?id=:id&self=true&context=addhints

a-hints : 
  url : 
    self : question/layout?id=:a&context=addhints
  show : 
    modal : m-edit-hints 
  update-on : question/preview

tab-resolution-pending :
  url : 
    self : pages/unresolved
    panel : unresolved/preview?id=:id

lnk-rotate-sg :
  update-on : suggestion/preview 

btn-upload-video-solution : 
  show : 
    modal : m-upload-video-solution

lnk-add-examiner : 
  show : 
    modal : m-new-examiner

tab-doubts-1 : 
  url :
    self : doubts/pending
    panel : doubt/preview?id=:id

a-refund-doubt : 
  url : 
    self : doubt/refund?id=:a
  update-on: doubt/preview tag/doubt
  disable-unless : tagged

a-solve-doubt : 
  show : 
    modal : m-upload-solution
  update-on : doubt/preview tag/doubt
  disable-unless : tagged

a-tag-doubt : 
  show : 
    modal : m-tag-doubt 
  update-on: doubt/preview tag/doubt
  disable-if : tagged

tab-stabs-1 : 
  url : 
    self : stab/dates 
    panel : stabs/dated?uid=:id
  autoclick : 
    tab : tab-stabs-2

tab-stabs-2 : 
  

tab-grade-1 :
  url : 
    self : exams/pending
    panel : load/rubric/for?e=:id
  autoclick :
    tab : tab-grade-2

tab-grade-2 :
  prev : tab-grade-1
  url :
    self : grade/pending?id=:prev
  autoclick :
    tab : tab-grade-3

tab-grade-3 : 
  prev : tab-grade-1
  id : tab-grade-2
  url : 
    self : scans/pending?q=:id&e=:prev
