
##############################################################################
## Landing page  
##############################################################################

m-about : 
  show : 
    menu : abouts 

btn-register : 
  show : 
    modal : m-register

btn-founders :
  show :
    modal : m-founders
