business_time:
  beginning_of_workday: 9:00 am
  end_of_workday: 6:00 pm
  holidays:
    - Jan 01, 2010
    - January 26th, 2014
    - March 17th, 2014 # holi
    - April 8th, 2014 # ram navami
    - April 18th, 2014 # good friday
    - May 14th, 2014 # buddha purnima
    - August 15th, 2014
    - August 18th, 2014 # janmashthami
    - October 2nd, 2014
    - October 23rd, 2014 # diwali
    - December 25th, 2010
  work_week:
    - mon
    - tue
    - wed
    - thu
    - fri
