
development :
  server : http://localhost:8080/axis2/services/documentMaster
  wsdl : http://localhost:8080/axis2/services/documentMaster?wsdl

production : 
  server : http://109.74.201.62:8080/axis2/services/documentMaster
  wsdl : http://109.74.201.62:8080/axis2/services/documentMaster?wsdl

test : 
  server : http://localhost:8080/axis2/services/documentMaster
  wsdl : http://localhost:8080/axis2/services/documentMaster?wsdl
