
server : 
  local: http://localhost:8080/axis2/services/documentMaster
  remote: http://109.74.201.62:8080/axis2/services/documentMaster

wsdl : 
  local : http://localhost:8080/axis2/services/documentMaster?wsdl
  remote : http://109.74.201.62:8080/axis2/services/documentMaster?wsdl
