
lnk-existing-quiz :
  left : 
    show : left-1
  wide : 
    show : wide-X 
  default-lnk : true
  autoclick :
    tab : tab-wsb-quizzes

tab-wsb-quizzes :
  toggle : tab
  ajax : quizzes/list
  panel :
    ajax : quiz/preview?id=:id

tab-wsb-sektions :
  toggle : tab
    
lnk-wsb-new :
  left : as-is
  wide : as-is
  autoclick :
    tab : tab-wsb-sektions

lnk-wsb-existing :
  left : as-is
  wide : as-is
  update-on : quiz/preview

lnk-download-solution :
  left : as-is 
  wide : as-is 
  update-on : quiz/preview

lnk-new-quiz :
  autoclick : 
    tab : tab-qzb-courses
  left :
    show : left-2
  wide :
    show : wide-wait

tab-qzb-courses : 
  toggle : tab
  ajax : teacher/courses
  autoclick :
    tab : tab-qzb-topics

tab-qzb-verticals :
  toggle : tab

tab-qzb-topics : 
  toggle : tab

tab-qzb-questions :
  toggle : tab
  panel : 
    ajax : question/preview?id=:id

m-teacher-quizzes :
  toggle : dropdown 
  menu : teacher-quiz

m-account :
  toggle : dropdown
  menu : tasks-on-account
