
##############################################################################
## Teachers 
##############################################################################

lnk-change-password :
  toggle : modal

lnk-existing-quiz :
  left : 
    show : left-1
  wide : 
    show : wide-X 
  default-lnk : true
  autoclick :
    tab : tab-wsb-quizzes

tab-wsb-quizzes :
  toggle : tab
  url : quizzes/list
  panel :
    url : quiz/preview?id=:id

tab-wsb-sektions :
  toggle : tab
    
lnk-wsb-new :
  left : as-is
  wide : as-is
  autoclick :
    tab : tab-wsb-sektions

lnk-wsb-existing :
  left : 
    show : left-3
  wide : as-is
  update-on : quiz/preview
  autoclick :
    tab : tab-wsl

tab-wsl :
  toggle : tab 
  url : quiz/testpapers.json?id=:prev
  prev : tab-wsb-quizzes
  panel :
    url : testpaper/load?id=:id

tab-wsl-quizzes :
  toggle : tab
  autoclick :
    link : lnk-existing-quiz

lnk-ws-download :
  left : as-is
  wide : as-is
  url : disabled
  update-on : testpaper/load

lnk-download-solution :
  left : as-is 
  wide : as-is 
  url : disabled 
  update-on : quiz/preview

lnk-new-quiz :
  autoclick : 
    tab : tab-qzb-courses
  left :
    show : left-2
  wide :
    show : wide-wait

lnk-wb-pending : 
  left :
    show : left-4
  wide : 
    show : wide-grd-canvas

tab-qzb-courses : 
  toggle : tab
  url : teacher/courses
  autoclick :
    tab : tab-qzb-topics

tab-qzb-verticals :
  toggle : tab

tab-qzb-topics : 
  toggle : tab

tab-qzb-questions :
  toggle : tab

m-teacher-quizzes :
  toggle : dropdown 
  menu : teacher-quiz

m-teacher-workbench : 
  toggle : dropdown
  menu : teacher-workbench

m-account :
  toggle : dropdown
  menu : tasks-on-account

lnk-ws-performance :
  left : 
    show : left-3
  wide :
    show : as-is
  autoclick :
    tab : tab-wsl

tab-ws-performance :
  toggle : tab
  panel : 
    url : student/performance.json?id=:id&ws=:prev 
  url : performance/ws.json?id=:prev 
  prev : tab-wsl
  autoclick :
    link : trapdoor-show-chart

trapdoor-show-chart :
  left : as-is
  wide : 
    show : graph-paper

##############################################################################
## Students 
##############################################################################

lnk-st-trigger : 
  autoclick :
    tab : tab-st-quizzes
  left : 
    show : left-1
  wide :
    show : wide-X
  default-lnk : true

tab-st-quizzes :
  toggle : tab
  url : student/testpapers
  panel :
    url : ws-preview.json?id=:id 

tab-st-feedback :
  toggle : tab
  url : student/feedback.json?id=:prev
  prev : tab-st-quizzes


##############################################################################
## Shared between Teachers, Examiners and Admin
##############################################################################

tab-honest :
  toggle : tab
  url : feedback.json?type=honest

tab-cogent :
  toggle : tab
  url : feedback.json?type=cogent

tab-complete :
  toggle : tab
  url : feedback.json?type=complete

tab-other :
  toggle : tab
  url : feedback.json?type=other
