
##############################################################################
## Teachers 
##############################################################################

lnk-edit-account :
  toggle : modal
  notouch : true

lnk-existing-quiz :
  default-lnk : true
  autoclick :
    tab : tab-wsb-quizzes
  left : 
    show : left-1
  wide : 
    show : wide-X 

lnk-edit-qz :
  autoclick :
    tab : tab-editqz-1
  left :
    show : left-7
  wide :
    show : wide-X

tab-editqz-1 : 
  url : quiz/questions.json?id=:prev
  panel :
    url : question/preview?id=:id
  prev : tab-wsb-quizzes

tab-wsb-quizzes :
  url : quizzes/list
  panel :
    url : quiz/preview?id=:id

tab-wsb-sektions :
    
lnk-wsb-new :
  notouch : true
  autoclick :
    tab : tab-wsb-sektions

lnk-wsb-existing :
  notouch : true
  update-on : quiz/preview
  autoclick :
    tab : tab-wsb-existing

tab-wsb-existing :
  url : quiz/testpapers.json?id=:prev
  prev : tab-wsb-quizzes
  panel :
    url : testpaper/load?id=:id

tab-wsl-quizzes :
  autoclick :
    link : lnk-existing-quiz

lnk-ws-download :
  notouch : true
  ajax : disabled
  update-on : testpaper/load

lnk-download-solution :
  notouch : true
  ajax : disabled
  update-on : quiz/preview pages/pending

lnk-suggestion-form :
  notouch : true
  ajax : disabled

lnk-upload-suggestion :
  toggle : modal
  notouch : true

lnk-new-quiz :
  autoclick : 
    tab : tab-qzb-1
  left :
    show : left-2
  wide :
    show : wide-wait

lnk-wb-pending : 
  left :
    show : left-4
  wide : 
    show : wide-grd-canvas
  autoclick :
    tab : tab-grd-ws

m-teacher-quizzes :
  toggle : dropdown 
  menu : teacher-quiz

m-teacher-workbench : 
  toggle : dropdown
  menu : teacher-workbench

m-report-cards :
  toggle : dropdown
  menu : teacher-rc

m-account :
  toggle : dropdown
  menu : tasks-on-account

m-howto : 
  toggle : dropdown
  menu : howto-guides

lnk-howto-1 : &type-notouch
  notouch : true

lnk-howto-2 : *type-notouch

tab-ws-performance :
  panel : 
    url : student/performance.json?id=:id&ws=:prev 
  url : performance/ws.json?id=:prev 
  prev : tab-wsl

tab-grd-ws :
  url : ws/pending
  autoclick :
    tab : tab-grd-page

tab-grd-page :
  prev : tab-grd-ws
  url : pages/pending.json?id=:prev
  autoclick :
    tab : tab-grd-panel

tab-grd-panel :
  prev : tab-grd-page
  id : tab-grd-ws
  url : gr/pending.json?page=:prev&ws=:id

tab-tc-rc-1 :
  url : ws/list
  panel :
    url : ws/summary.json?id=:id
  autoclick :
    tab : tab-tc-rc-2

tab-tc-rc-2 :
  panel :
    url : ws/layout.json?ws=:prev&id=:id
  prev : tab-tc-rc-1
  wide :
    show : wide-chart-1
  autoclick :
    tab : tab-tc-rc-3

tab-tc-rc-3 :
  wide :
    show : wide-X

lnk-tc-rc :
  left : 
    show : left-5
  wide :
    show : wide-wait
  autoclick :
    tab : tab-tc-rc-1

lnk-ws-publish :
  notouch: true
  url : ws/publish.json?id=:id
  id : tab-wsb-existing

lnk-ws-unpublish :
  notouch: true
  url : ws/unpublish.json?id=:id
  id : tab-wsb-existing

lnk-rc-deepdive :
  left : 
    show : left-6
  wide :
    show : wide-chart-2
  autoclick :
    tab : tab-dive-1

tab-dive-1 :
  url : teacher/sektions?context=deepdive
  panel : 
    url : sektion/students.json?id=:id&context=deepdive
  autoclick : 
    tab : tab-dive-2

tab-dive-2 :
  prev : tab-dive-1
  wide :
    show : wide-chart-2

tab-dive-3 : 
  prev : tab-dive-1
  panel :
    url : overall/proficiency.json?id=:id
  wide :
    show : wide-chart-3

deepdive-* : 
  url : vertical/topics?id=:id&context=deepdive
  panel :
    url : sektion/proficiency?of=:prev&in=:id
  prev : tab-dive-1

lnk-mng-sektions :
  left : 
    show : left-8
  middle :
    show : middle-1
  autoclick :
    tab : tab-mng-sektions-1

tab-mng-sektions-1 :
  url : teacher/sektions?context=edit
  panel : 
    url : ping/sektion?id=:id

help-* :
  notouch : true

##############################################################################
## Students 
##############################################################################

lnk-st-rc : 
  autoclick :
    tab : tab-st-rc-1
  left : 
    show : left-1
  wide :
    show : wide-wait
  default-lnk : true

lnk-st-inbox :
  autoclick :
    tab : tab-st-inbox
  left : 
    show : left-2 
  wide :
    show : wide-wait

tab-st-rc-1 :
  url : ws/list 
  panel :
    url : ws/layout.json?ws=:id&id=:prev
  prev : control-panel
  autoclick :
    tab : tab-st-rc-2

tab-st-rc-2 :
  prev : tab-st-rc-1

tab-st-inbox :
  url : inbox.json?id=:prev
  prev : control-panel
  panel :
    url : inbox/echo.json?ws=:id

tab-st-outbox :
  url : outbox

lnk-inbox-download :
  notouch: true
  ajax: disabled
  update-on : inbox/echo

m-enroll-self : 
  toggle : dropdown 
  menu : enrollment-form

##############################################################################
## Admin Only 
##############################################################################

##############################################################################
## Admin / Examiner specific  
##############################################################################

m-admin-wb :
  toggle : dropdown 
  menu : admin-wb

m-admin-schools :
  toggle : dropdown 
  menu : admin-schools 

lnk-wb-receive :
  notouch : true 
  url : receive/scans

lnk-mng-topics : 
  left : 
    show : left-2
  autoclick :
    tab : tab-mng-topics-1

tab-mng-topics-1 :
  url : verticals/list
  panel :
    url : vertical/topics?id=:id

tab-mng-topics-2 :

lnk-wb-schools :
  left :
    show : left-1
  wide :
    show : wide-1
  url : schools/list

lnk-wb-blockdb :
  notouch : true
  url : examiner/block_db_slots.json?id=:id
  id : control-panel

m-examiner-wb :
  toggle : dropdown 
  menu : examiner-wb

tab-new-school :

tab-selected-school :

tab-school-general :

tab-school-faculty :

tab-school-sektions :

lnk-wb-tagging :
  left :
    show : left-3
  wide :
    show : wide-X
  autoclick :
    tab : tab-tag-pending

tab-tag-pending :
  url : untagged/list
  panel :
    url : question/preview.json?id=:id
  autoclick :
    tab : tab-tag-topic

tab-tag-topic :

tab-tag-misc :

lnk-wb-typeset :
  left :
    show : left-5
  wide :
    show : wide-X
  autoclick :
    tab : tab-typeset-new

tab-typeset-new :
  url : typeset/new
  panel :
    url : suggestion/preview.json?id=:id

lnk-block-* : 
  notouch : true
  id : tab-typeset-new

m-block-slots :
  menu : blockdb-slots
  toggle : dropdown

tab-typeset-ongoing :
  url : typeset/ongoing
  panel :
    url : suggestion/preview.json?id=:id

##############################################################################
## Shared between Teachers, Examiners and Admin
##############################################################################

tab-honest :

tab-cogent :

tab-complete :

tab-other :

##############################################################################
## Shared between ** all ** roles  
##############################################################################

lnk-logout :
  notouch : true

m-downloads : 
  menu : user-downloads
  toggle : dropdown

m-registrations : 
  menu : user-registrations
  toggle : dropdown

lnk-register-student :
  toggle : modal

lnk-register-teacher :
  toggle : modal

m-notifications :
  menu : notifications
  toggle : dropdown

