
lnk-existing-quiz :
  left : 
    show : left-1
  wide : 
    show : wide-X 
  default-lnk : true
  autoclick :
    tab : tab-wsb-quizzes

tab-wsb-quizzes :
  toggle : tab
  ajax : quizzes/list
  panel-ajax : quiz/preview?id=:id

tab-wsb-sektions :
  toggle : tab
    
