
rubric :
  maths :
    overall :
      0 :
        weight : 4
        text : It's blank!
      1 : 
        weight : 0
        text : No / very doubtful
      2 : 
        weight : 3
        text : Perhaps / can't be sure
      3 : 
        weight : 4
        text : Yes / no doubt

    cogency :
      0 : 
        weight : 0
        text : Irrelevant
      1 : 
        weight : 0
        text : Hardly 
      2 : 
        weight : 1
        text : Somewhat - but not much
      3 : 
        weight : 2
        text : Partially / half-baked
      4 : 
        weight : 3
        text : Mostly
      5 : 
        weight : 4
        text : Yes

    completeness : 
      0 : 
        weight : 0
        text : Irrelevant
      1 : 
        weight : 0
        text : Hardly 
      2 : 
        weight : 1
        text : Somewhat - but not much
      3 : 
        weight : 2
        text : Partially / half-baked
      4 : 
        weight : 3
        text : Mostly
      5 : 
        weight : 4
        text : Yes

    other :
      0 :
        penalty : true
        text : Calculation Mistake(s)
      1 :
        penalty : true
        text : Mis-/Over-interpreted the question
      2 :
        penalty : true
        text : Unexplained jumps in logic
      3 :
        penalty : true
        text : Not all loose ends tied up
      4 :
        penalty : true
        text : Made invalid assumptions
      5 :
        penalty : true
        text : Solution not mathematically sound
      6 :
        penalty : true
        text :
      7 : 
        penalty : true
        text :
      8 :
        penalty : true
        text :
      9 :
        penalty : true
        text :
      10 :
        penalty : true
        text :
      11 :
        penalty : true
        text :
